# -*- coding: utf-8 -*-
"""App_SS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fMjsuN2JcHDTEP3p65GbnNfBcWiPXUc0
"""

import streamlit as st
import pandas as pd
import os
from PIL import Image
from datetime import datetime
import uuid

# --------------------
# Config & storage
# --------------------
DATA_DIR = "data"
UPLOAD_DIR = "uploads"
os.makedirs(DATA_DIR, exist_ok=True)
os.makedirs(UPLOAD_DIR, exist_ok=True)

LISTINGS_CSV = os.path.join(DATA_DIR, "listings.csv")
BIDS_CSV = os.path.join(DATA_DIR, "bids.csv")
USERS_CSV = os.path.join(DATA_DIR, "users.csv")
RATINGS_CSV = os.path.join(DATA_DIR, "ratings.csv")

# Initialize dataframes safely
def load_df(path, cols):
    if os.path.exists(path):
        try:
            return pd.read_csv(path)
        except Exception:
            return pd.DataFrame(columns=cols)
    else:
        return pd.DataFrame(columns=cols)

listings_cols = ["listing_id","user_email","name","phone","address","landmark","lat","lon",
                 "category","subcategory","volume","weight","collection_date","collection_time",
                 "image_path","status","created_at","accepted_bid_id"]

bids_cols = ["bid_id","listing_id","bidder_email","bidder_name","price","message","created_at","status"]
users_cols = ["email","name","phone","role","company","verified","joined_at"]
ratings_cols = ["rating_id","listing_id","user_email","recycler_email","rating","comment","created_at"]

listings = load_df(LISTINGS_CSV, listings_cols)
bids = load_df(BIDS_CSV, bids_cols)
users = load_df(USERS_CSV, users_cols)
ratings = load_df(RATINGS_CSV, ratings_cols)

# Save helper
def save_df(df, path):
    df.to_csv(path, index=False)

# --------------------
# Small helpers
# --------------------
def gen_id(prefix="L"):
    return f"{prefix}_{uuid.uuid4().hex[:8]}"

def append_row(df, row, path):
    new_df = pd.concat([df, pd.DataFrame([row])], ignore_index=True)
    save_df(new_df, path)
    return new_df

def update_df(df, path):
    save_df(df, path)

def ai_suggest_category_and_price(image_path, subcategory, volume, weight):
    """
    Simple heuristic 'AI' placeholder:
    - If subcategory contains 'plastic' -> low price
    - If weight large or volume>100 -> higher price for bulky scrap
    - Returns (category_label, suggested_price_range_low, suggested_price_range_high)
    """
    cat = subcategory or "Mixed"
    low = 50
    high = 200
    try:
        w = float(weight or 0)
        v = float(volume or 0)
    except:
        w, v = 0, 0

    if "plastic" in cat.lower():
        low, high = 20, 100
    elif "metal" in cat.lower() or "iron" in cat.lower() or "copper" in cat.lower():
        low, high = 200, 1000
    elif "electronics" in cat.lower() or "e-waste" in cat.lower():
        low, high = 300, 1500
    elif v > 200 or w > 100:
        low, high = 150, 800
    else:
        low, high = 50, 300

    return cat.title(), int(low), int(high)

# --------------------
# Session state for auth (demo)
# --------------------
if "user" not in st.session_state:
    st.session_state.user = None

# --------------------
# UI Layout
# --------------------
st.set_page_config(page_title="Smart Swachh Marketplace (Phase 2)", layout="wide")
st.title("Smart Swachh — Zero Waste Nykaa (Advanced Marketplace Prototype)")
st.markdown("List your waste, get competitive bids from verified recyclers, choose best offer, schedule pickup.")

# --------------------
# Simple Auth
# --------------------
st.sidebar.header("User Login / Register")
auth_action = st.sidebar.selectbox("I am a", ["Guest", "Citizen", "Recycler"])
email_input = st.sidebar.text_input("Email")
name_input = st.sidebar.text_input("Name")
phone_input = st.sidebar.text_input("Phone (optional)")
company_input = st.sidebar.text_input("Company / Organization (optional)")

if st.sidebar.button("Register / Login"):
    if not email_input:
        st.sidebar.error("Please enter email to register/login.")
    else:
        # Check existing user
        if not users.empty and email_input in users["email"].values:
            # login
            st.session_state.user = users[users["email"] == email_input].iloc[0].to_dict()
            st.sidebar.success(f"Logged in as {st.session_state.user['name'] or email_input}")
        else:
            # register new
            new_user = {
                "email": email_input,
                "name": name_input or email_input.split("@")[0],
                "phone": phone_input or "",
                "role": auth_action,
                "company": company_input or "",
                "verified": False,
                "joined_at": datetime.utcnow().isoformat()
            }
            users = append_row(users, new_user, USERS_CSV)
            st.session_state.user = new_user
            st.sidebar.success("Registered and logged in (demo)")

if st.sidebar.button("Logout"):
    st.session_state.user = None
    st.sidebar.info("Logged out")

# --------------------
# Main Tabs
# --------------------
tabs = st.tabs(["Home / Create Listing", "Browse Listings", "Recycler Dashboard", "My Listings / Bids", "Admin"])
tab = tabs[0]

# --------------------
# Tab: Home / Create Listing
# --------------------
with tabs[0]:
    st.header("Create Waste Listing")
    st.info("Citizens/Businesses can list e-waste, bulky items, or scrap for bidding.")

    if st.session_state.user is None or st.session_state.user.get("role") != "Citizen":
        st.warning("Please register/login as a Citizen (sidebar) to create a listing.")
    else:
        with st.form("create_listing", clear_on_submit=True):
            name = st.text_input("Contact Name", value=st.session_state.user.get("name"))
            phone = st.text_input("Phone", value=st.session_state.user.get("phone"))
            address = st.text_area("Address")
            landmark = st.text_input("Landmark (optional)")
            lat = st.text_input("Latitude (optional)")
            lon = st.text_input("Longitude (optional)")
            category = st.selectbox("Category", ["E-Waste", "Bulky Waste", "Metal Scrap", "Plastic", "Furniture", "Other"])
            subcategory = st.text_input("Subcategory (e.g., fridge, sofa, tv, copper wires)")
            volume = st.number_input("Approx Volume (in liters)", min_value=0.0, value=10.0)
            weight = st.number_input("Approx Weight (in kg)", min_value=0.0, value=5.0)
            collection_date = st.date_input("Preferred collection date")
            collection_time = st.time_input("Preferred time")
            photo = st.file_uploader("Upload photo of the waste item", type=["jpg","jpeg","png"])

            submit = st.form_submit_button("Create Listing")

        if submit:
            listing_id = gen_id("L")
            img_path = ""
            if photo:
                fname = f"{listing_id}.jpg"
                path = os.path.join(UPLOAD_DIR, fname)
                img = Image.open(photo)
                img = img.convert("RGB")
                img.save(path, format="JPEG", quality=85)
                img_path = path

            # AI suggest (mock)
            suggested_cat, low_price, high_price = ai_suggest_category_and_price(img_path, subcategory, volume, weight)

            row = {
                "listing_id": listing_id,
                "user_email": st.session_state.user["email"],
                "name": name,
                "phone": phone,
                "address": address,
                "landmark": landmark,
                "lat": lat,
                "lon": lon,
                "category": category,
                "subcategory": subcategory,
                "volume": volume,
                "weight": weight,
                "collection_date": collection_date.isoformat(),
                "collection_time": collection_time.strftime("%H:%M"),
                "image_path": img_path,
                "status": "Open",
                "created_at": datetime.utcnow().isoformat(),
                "accepted_bid_id": ""
            }
            listings = append_row(listings, row, LISTINGS_CSV)
            st.success(f"Listing created: {listing_id}")
            st.info(f"Suggested price range (demo): ₹{low_price} - ₹{high_price}")

# --------------------
# Tab: Browse Listings (for public/recyclers)
# --------------------
with tabs[1]:
    st.header("Browse Open Listings")
    st.info("Anyone can browse open listings. Recyclers should register and login on the sidebar to bid.")
    view_df = listings[listings["status"] == "Open"].sort_values("created_at", ascending=False)
    if view_df.empty:
        st.info("No open listings at the moment.")
    else:
        for idx, row in view_df.iterrows():
            st.markdown("---")
            cols = st.columns([1,2])
            with cols[0]:
                if row.get("image_path") and os.path.exists(row["image_path"]):
                    st.image(row["image_path"], width=220)
                else:
                    st.image("https://via.placeholder.com/220x150.png?text=No+Image", width=220)
            with cols[1]:
                st.subheader(f"{row['category']} — {row['subcategory'] or 'General'}")
                st.write(f"ID: {row['listing_id']}")
                st.write(f"Location: {row['address']} • {row['landmark']}")
                st.write(f"Volume: {row['volume']} L • Weight: {row['weight']} kg")
                st.write(f"Preferred: {row['collection_date']} @ {row['collection_time']}")
                st.write(f"Status: {row['status']}")
                if st.session_state.user and st.session_state.user.get("role") == "Recycler":
                    bid_name = st.text_input(f"Your business name for {row['listing_id']}", key=f"bn_{row['listing_id']}")
                    bid_price = st.number_input(f"Your bid (₹) for {row['listing_id']}", min_value=0, key=f"bp_{row['listing_id']}")
                    bid_msg = st.text_area(f"Message (optional) for {row['listing_id']}", key=f"bm_{row['listing_id']}")
                    if st.button(f"Place Bid on {row['listing_id']}", key=f"bidbtn_{row['listing_id']}"):
                        bid_id = gen_id("B")
                        bid_row = {
                            "bid_id": bid_id,
                            "listing_id": row["listing_id"],
                            "bidder_email": st.session_state.user["email"],
                            "bidder_name": bid_name or st.session_state.user.get("company") or st.session_state.user.get("name"),
                            "price": bid_price,
                            "message": bid_msg,
                            "created_at": datetime.utcnow().isoformat(),
                            "status": "Open"
                        }
                        bids = append_row(bids, bid_row, BIDS_CSV)
                        st.success(f"Bid submitted: {bid_id}")

# --------------------
# Tab: Recycler Dashboard
# --------------------
with tabs[2]:
    st.header("Recycler Dashboard")
    if st.session_state.user is None or st.session_state.user.get("role") != "Recycler":
        st.warning("Please register/login as a Recycler (sidebar) to access this dashboard.")
    else:
        st.subheader("Your Active Bids")
        my_bids = bids[bids["bidder_email"] == st.session_state.user["email"]]
        if my_bids.empty:
            st.info("You have not placed any bids yet.")
        else:
            st.table(my_bids[["bid_id","listing_id","price","status","created_at"]].sort_values("created_at", ascending=False))

        st.subheader("Accepted Jobs")
        accepted = bids[(bids["bidder_email"] == st.session_state.user["email"]) & (bids["status"] == "Accepted")]
        if accepted.empty:
            st.info("No accepted jobs.")
        else:
            for _, b in accepted.iterrows():
                listing_id = b["listing_id"]
                listing_row = listings[listings["listing_id"] == listing_id]
                if listing_row.empty:
                    continue
                listing_row = listing_row.iloc[0]
                st.markdown(f"**Job:** {listing_id} • {listing_row['category']} - {listing_row['subcategory']}")
                st.write(f"Address: {listing_row['address']}")
                if st.button(f"Mark Picked Up: {b['bid_id']}", key=f"picked_{b['bid_id']}"):
                    # update bid status and listing status
                    bids.loc[bids["bid_id"] == b["bid_id"], "status"] = "PickedUp"
                    update_df(bids, BIDS_CSV)
                    listings.loc[listings["listing_id"] == listing_id, "status"] = "PickedUp"
                    listings.loc[listings["listing_id"] == listing_id, "accepted_bid_id"] = b["bid_id"]
                    update_df(listings, LISTINGS_CSV)
                    st.success("Marked as PickedUp. Please confirm after delivery in user's panel.")

# --------------------
# Tab: My Listings / Bids (Citizen view)
# --------------------
with tabs[3]:
    st.header("My Listings & Bids")
    if st.session_state.user is None:
        st.warning("Please login to view your listings and bids.")
    else:
        user_email = st.session_state.user["email"]
        my_listings = listings[listings["user_email"] == user_email].sort_values("created_at", ascending=False)
        if my_listings.empty:
            st.info("You have no listings yet.")
        else:
            for _, L in my_listings.iterrows():
                st.markdown("---")
                cols = st.columns([1,2])
                with cols[0]:
                    if L["image_path"] and os.path.exists(L["image_path"]):
                        st.image(L["image_path"], width=200)
                    else:
                        st.image("https://via.placeholder.com/200x140.png?text=No+Image", width=200)
                with cols[1]:
                    st.write(f"Listing ID: {L['listing_id']}")
                    st.write(f"Category: {L['category']} • {L['subcategory']}")
                    st.write(f"Status: {L['status']}")
                    # show bids for this listing
                    listing_bids = bids[bids["listing_id"] == L["listing_id"]].sort_values("created_at", ascending=False)
                    if listing_bids.empty:
                        st.write("No bids yet.")
                    else:
                        st.write("Bids:")
                        for _, b in listing_bids.iterrows():
                            st.write(f"- {b['bidder_name']} • ₹{b['price']} • {b['message']}")
                            if st.button(f"Accept {b['bid_id']} for {L['listing_id']}", key=f"accept_{b['bid_id']}"):
                                # Accept bid: update bid status and listing
                                bids.loc[bids["bid_id"] == b["bid_id"], "status"] = "Accepted"
                                update_df(bids, BIDS_CSV)
                                listings.loc[listings["listing_id"] == L["listing_id"], "status"] = "Accepted"
                                listings.loc[listings["listing_id"] == L["listing_id"], "accepted_bid_id"] = b["bid_id"]
                                update_df(listings, LISTINGS_CSV)
                                st.success(f"Accepted bid {b['bid_id']}. Please wait for recycler to pickup.")
                        # If accepted, allow rating once picked up
                        if L["status"] == "PickedUp" and L["accepted_bid_id"]:
                            accepted_bid = bids[bids["bid_id"] == L["accepted_bid_id"]]
                            if not accepted_bid.empty:
                                rec_email = accepted_bid.iloc[0]["bidder_email"]
                                if st.button(f"Confirm Delivery & Rate Recycler {accepted_bid.iloc[0]['bidder_name']}", key=f"ratebtn_{L['listing_id']}"):
                                    rating_id = gen_id("R")
                                    rate_row = {
                                        "rating_id": rating_id,
                                        "listing_id": L["listing_id"],
                                        "user_email": user_email,
                                        "recycler_email": rec_email,
                                        "rating": 5,
                                        "comment": "Good pickup (demo)",
                                        "created_at": datetime.utcnow().isoformat()
                                    }
                                    ratings = append_row(ratings, rate_row, RATINGS_CSV)
                                    listings.loc[listings["listing_id"] == L["listing_id"], "status"] = "Closed"
                                    update_df(listings, LISTINGS_CSV)
                                    st.success("Thank you! Recycler rated and listing closed.")

# --------------------
# Tab: Admin utilities
# --------------------
with tabs[4]:
    st.header("Admin / Export")
    st.write("Download CSVs or reset demo data (careful).")
    if st.button("Download Listings CSV"):
        st.download_button("Download Listings", data=open(LISTINGS_CSV,"rb"), file_name="listings.csv")
    if st.button("Download Bids CSV"):
        st.download_button("Download Bids", data=open(BIDS_CSV,"rb"), file_name="bids.csv")
    if st.button("Download Users CSV"):
        st.download_button("Download Users", data=open(USERS_CSV,"rb"), file_name="users.csv")
    if st.button("Download Ratings CSV"):
        st.download_button("Download Ratings", data=open(RATINGS_CSV,"rb"), file_name="ratings.csv")

    if st.button("Reset Demo Data (delete CSVs)"):
        for p in [LISTINGS_CSV, BIDS_CSV, USERS_CSV, RATINGS_CSV]:
            try:
                os.remove(p)
            except Exception:
                pass
        st.success("Demo data reset. Reload the app to initialize blank dataframes.")
