# -*- coding: utf-8 -*-
"""App_SS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fMjsuN2JcHDTEP3p65GbnNfBcWiPXUc0
"""

import streamlit as st
import pandas as pd
from PIL import Image
import datetime

st.set_page_config(page_title="Smart Swachh Marketplace", layout="wide")

st.title("♻️ Smart Swachh – Waste Listing Marketplace")
st.write("List your waste → Receive bids → Choose best offer → Schedule pickup")

# Load or create bidding database
try:
    listings = pd.read_csv("listings.csv")
except:
    listings = pd.DataFrame(columns=[
        "name","phone","email","address","landmark","lat","lon",
        "category","subcategory","volume","weight",
        "collection_date","collection_time",
        "image_path","status","listing_id"
    ])

try:
    bids = pd.read_csv("bids.csv")
except:
    bids = pd.DataFrame(columns=["listing_id","bidder","price","message"])

# ---------------------------
# STEP 1: WASTE LISTING FORM
# ---------------------------

st.header("📤 Create a Waste Listing")

with st.form("listing_form"):
    name = st.text_input("Full Name")
    phone = st.text_input("Phone Number")
    email = st.text_input("Email")
    address = st.text_area("Address")
    landmark = st.text_input("Landmark (optional)")

    lat = st.number_input("Latitude", value=0.0)
    lon = st.number_input("Longitude", value=0.0)

    category = st.selectbox("Waste Category", ["E-Waste","Bulky Waste","Metal Scrap","Plastic","Furniture"])
    subcategory = st.text_input("Sub-category")

    volume = st.number_input("Approx Volume (cubic ft)", value=1)
    weight = st.number_input("Approx Weight (kg)", value=1)

    collection_date = st.date_input("Preferred Collection Date")
    collection_time = st.time_input("Preferred Time Window")

    photo = st.file_uploader("Upload Waste Photo", type=["jpg","png","jpeg"])

    submitted = st.form_submit_button("Create Listing")

if submitted:
    listing_id = len(listings) + 1
    img_path = f"uploads/{listing_id}.jpg"

    if photo:
        img = Image.open(photo)
        img.save(img_path)

    new_row = {
        "name": name, "phone": phone, "email": email,
        "address": address, "landmark": landmark,
        "lat": lat, "lon": lon,
        "category": category, "subcategory": subcategory,
        "volume": volume, "weight": weight,
        "collection_date": collection_date,
        "collection_time": collection_time,
        "image_path": img_path,
        "status": "Open",
        "listing_id": listing_id
    }

    listings = listings.append(new_row, ignore_index=True)
    listings.to_csv("listings.csv", index=False)

    st.success(f"Listing Created Successfully! Listing ID: {listing_id}")

# ---------------------------
# STEP 2: RECYCLER BIDDING
# ---------------------------

st.header("💼 Recycler Dashboard – Place Bids")

listing_ids = listings["listing_id"].unique()

select_listing = st.selectbox("Select Listing to Bid On", listing_ids)

selected_data = listings[listings["listing_id"] == select_listing].iloc[0]

st.image(selected_data["image_path"], width=300)
st.write(f"Category: {selected_data['category']}")
st.write(f"Location: {selected_data['address']}")

bidder_name = st.text_input("Your Name (Recycling Company)")
bid_price = st.number_input("Your Bid Price (₹)")
bid_msg = st.text_area("Message to Seller")

if st.button("Submit Bid"):
    bid_row = {
        "listing_id": select_listing,
        "bidder": bidder_name,
        "price": bid_price,
        "message": bid_msg
    }
    bids = bids.append(bid_row, ignore_index=True)
    bids.to_csv("bids.csv", index=False)
    st.success("Bid Submitted Successfully!")

# ---------------------------
# STEP 3: VIEW BIDS
# ---------------------------

st.header("📊 View Bids for Your Listing")

my_listing = st.selectbox("Select Your Listing", listing_ids)
user_bids = bids[bids["listing_id"] == my_listing]

st.table(user_bids)